name = "roomy-discord-iputapp"
main = "src/index.ts"
compatibility_date = "2025-01-27"

compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[triggers]
# 実行スケジュール
# - 月曜日 15:30 JST (06:30 UTC)
# - 火曜日 15:30 JST (06:30 UTC)
crons = ["30 6 * * 1", "30 6 * * 2"]
